### ISSUE TITLE
OSError: Could not build egg 

### ISSUE THREAD

**Issue by folmer** [JHUISI/charm#119]
Hello,

Recently I tried to install Charm-Crypt but I ran into this error and I don't know why this happens:

```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    use_setuptools() #bootstrap installs Distribute if not installed
  File "/home/folmer/Documents/python/Charm-Crypto-0.43/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/folmer/Documents/python/Charm-Crypto-0.43/distribute_setup.py", line 125, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "/home/folmer/Documents/python/Charm-Crypto-0.43/distribute_setup.py", line 116, in _build_egg
    raise IOError('Could not build the egg.')
OSError: Could not build the egg.
```

I have all the dependencies installed, python3, pyparsing, pdc, gmp and openssl. All the latest version.
Does someone know why I get this error?

**Comment by dennisschroer** [comment]
How did you try to install charm? How did you download it? Which commands did you use?

**Comment by dennisschroer** [comment]
Also, installing python3-dev (`apt install python3-dev`) could help, this contains packages for building and distributing python modules

**Comment by folmer** [comment]
I downloaded Charm via the download page(Charm-Crypto-0.43_Python3.tar.gz (Python 3.x Source)) and tried to install it using ./configure.sh, sudo make and sudo make install. The ./configure.sh gives:

```
Install prefix    /usr/local
data directory    /usr/local/share/charm
binary directory  /usr/local/bin
library directory /usr/local/lib
config directory  /usr/local/etc
Source path       /home/folmer/Documents/python/Charm-Crypto-0.43
CFLAGS            -O2 -g 
CHARM_CFLAGS       -m64 -Wall -Wundef -Wwrite-strings -Wmissing-prototypes  -fstack-protector-all -Wendif-labels -Wmissing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-declaration -Wold-style-definition -Wtype-limits
LDFLAGS           -m64 
make              make
python            /usr/bin/python3
build_ext options build_ext 
install           install
host CPU          x86_64
wget              /usr/bin/wget
gprof enabled     no
profiler          no
static build      no
-Werror enabled   no
integer module    yes
ecc module        yes
pairing module    yes
disable benchmark no
libm found        yes
libgmp found      yes
libpbc found      yes
libcrypto found   yes
Documentation     no
```

, which seems fine. The sudo make command gives the error specified in the initial post. I have python3-dev installed so that should not be a problem.

**Comment by emm-1** [comment]
Hi. What you did to resolve this problem ?

**Comment by XiaoShanQing-cmyk** [comment]
I’ve met the same question. Has anyone solved it?

**Comment by manpreet-sangha** [comment]
Similar sort of issue whilst trying to:
 sudo make

Traceback (most recent call last):
  File "/tmp/tmppl205lra/distribute-0.6.42/setup.py", line 45, in <module>
    exec(init_file.read(), d)
  File "<string>", line 8, in <module>
  File "/tmp/tmppl205lra/distribute-0.6.42/build/src/setuptools/__init__.py", line 2, in <module>
    from setuptools.extension import Extension, Library
  File "/tmp/tmppl205lra/distribute-0.6.42/build/src/setuptools/extension.py", line 5, in <module>
    from setuptools.dist import _get_unpatched
  File "/tmp/tmppl205lra/distribute-0.6.42/build/src/setuptools/dist.py", line 6, in <module>
    from setuptools.command.install import install
  File "/tmp/tmppl205lra/distribute-0.6.42/build/src/setuptools/command/__init__.py", line 8, in <module>
    from setuptools.command import install_scripts
  File "/tmp/tmppl205lra/distribute-0.6.42/build/src/setuptools/command/install_scripts.py", line 3, in <module>
    from pkg_resources import Distribution, PathMetadata, ensure_directory
  File "/tmp/tmppl205lra/distribute-0.6.42/build/src/pkg_resources.py", line 1336, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
**AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'**
/home/mike/charm/Charm-Crypto-0.43/distribute-0.6.42-py3.10.egg
Traceback (most recent call last):
  File "/home/mike/charm/Charm-Crypto-0.43/distribute_setup.py", line 143, in use_setuptools
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/charm/Charm-Crypto-0.43/setup.py", line 2, in <module>
    use_setuptools() #bootstrap installs Distribute if not installed
  File "/home/mike/charm/Charm-Crypto-0.43/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/mike/charm/Charm-Crypto-0.43/distribute_setup.py", line 125, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "/home/mike/charm/Charm-Crypto-0.43/distribute_setup.py", line 116, in _build_egg
    raise IOError('Could not build the egg.')
OSError: Could not build the egg.
make: *** [Makefile:28: all] Error 1

**Comment by jakinyele** [comment]
Closing as part of issue cleanup — this issue is very old and likely no longer relevant with the current codebase (v0.63). Feel free to reopen if still applicable.
