### ISSUE TITLE
OS X fails to install. Linux has no problems

### ISSUE THREAD

**Issue by CraigglesO** [JHUISI/charm#150]
This was my install process using the dev branch:
`./configure.sh --enable-darwin`
`sudo make install`

and `sudo make test`:
```
================================================== test session starts ===================================================
platform darwin -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /Users/craigoconnor/Desktop/charm, inifile: pytest.ini
collected 0 items / 172 errors                                                                                            

========================================================= ERRORS =========================================================
_________________________________ ERROR collecting charm/adapters/abenc_adapt_hybrid.py __________________________________
charm/toolbox/pairinggroup.py:3: in <module>
    from charm.core.math.pairing import pairing,pc_element,ZR,G1,G2,GT,init,pair,hashPair,H,random,serialize,deserialize,ismember,order
E   SystemError: initialization of pairing failed without raising an exception

During handling of the above exception, another exception occurred:
charm/adapters/abenc_adapt_hybrid.py:3: in <module>
    from charm.schemes.abenc.abenc_bsw07 import CPabe_BSW07
charm/schemes/abenc/abenc_bsw07.py:16: in <module>
    from charm.toolbox.pairinggroup import PairingGroup,ZR,G1,G2,GT,pair
charm/toolbox/pairinggroup.py:8: in <module>
    exit(-1)
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_sitebuiltins.py:26: in __call__
    raise SystemExit(code)
E   SystemExit: -1



......




---------------------------------------------------- Captured stdout -----------------------------------------------------
Type does not define the tp_name field.
____________________________________ ERROR collecting charm/toolbox/paddingschemes.py ____________________________________
charm/toolbox/paddingschemes.py:3: in <module>
    from charm.toolbox.securerandom import SecureRandomFactory
charm/toolbox/securerandom.py:6: in <module>
    from charm.toolbox.conversion import Conversion
charm/toolbox/conversion.py:7: in <module>
    from charm.core.math.integer import integer
E   SystemError: Type does not define the tp_name field.
_________________________________ ERROR collecting charm/toolbox/paddingschemes_test.py __________________________________
charm/toolbox/paddingschemes_test.py:6: in <module>
    from  charm.toolbox.paddingschemes import OAEPEncryptionPadding, MGF1, hashFunc, PSSPadding, PKCS7Padding
charm/toolbox/paddingschemes.py:3: in <module>
    from charm.toolbox.securerandom import SecureRandomFactory
charm/toolbox/securerandom.py:6: in <module>
    from charm.toolbox.conversion import Conversion
charm/toolbox/conversion.py:7: in <module>
    from charm.core.math.integer import integer
E   SystemError: Type does not define the tp_name field.
_________________________________ ERROR collecting charm/toolbox/paddingschemes_test.py __________________________________
charm/toolbox/paddingschemes_test.py:6: in <module>
    from  charm.toolbox.paddingschemes import OAEPEncryptionPadding, MGF1, hashFunc, PSSPadding, PKCS7Padding
charm/toolbox/paddingschemes.py:3: in <module>
    from charm.toolbox.securerandom import SecureRandomFactory
charm/toolbox/securerandom.py:6: in <module>
    from charm.toolbox.conversion import Conversion
charm/toolbox/conversion.py:7: in <module>
    from charm.core.math.integer import integer
E   SystemError: Type does not define the tp_name field.
_____________________________________ ERROR collecting charm/toolbox/pairinggroup.py _____________________________________
charm/toolbox/pairinggroup.py:3: in <module>
    from charm.core.math.pairing import pairing,pc_element,ZR,G1,G2,GT,init,pair,hashPair,H,random,serialize,deserialize,ismember,order
E   SystemError: initialization of pairing failed without raising an exception

During handling of the above exception, another exception occurred:
charm/toolbox/pairinggroup.py:8: in <module>
    exit(-1)
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_sitebuiltins.py:26: in __call__
    raise SystemExit(code)
E   SystemExit: -1
---------------------------------------------------- Captured stdout -----------------------------------------------------
initialization of pairing failed without raising an exception
__________________________________ ERROR collecting charm/toolbox/redundancyschemes.py ___________________________________
charm/toolbox/redundancyschemes.py:3: in <module>
    from charm.toolbox.securerandom import SecureRandomFactory
charm/toolbox/securerandom.py:6: in <module>
    from charm.toolbox.conversion import Conversion
charm/toolbox/conversion.py:7: in <module>
    from charm.core.math.integer import integer
E   SystemError: Type does not define the tp_name field.
_____________________________________ ERROR collecting charm/toolbox/secretshare.py ______________________________________
charm/toolbox/pairinggroup.py:3: in <module>
    from charm.core.math.pairing import pairing,pc_element,ZR,G1,G2,GT,init,pair,hashPair,H,random,serialize,deserialize,ismember,order
E   SystemError: initialization of pairing failed without raising an exception

During handling of the above exception, another exception occurred:
charm/toolbox/secretshare.py:2: in <module>
    from charm.toolbox.pairinggroup import PairingGroup,ZR,order
charm/toolbox/pairinggroup.py:8: in <module>
    exit(-1)
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_sitebuiltins.py:26: in __call__
    raise SystemExit(code)
E   SystemExit: -1
---------------------------------------------------- Captured stdout -----------------------------------------------------
initialization of pairing failed without raising an exception
______________________________________ ERROR collecting charm/toolbox/secretutil.py ______________________________________
charm/toolbox/secretutil.py:5: in <module>
    from charm.core.math.pairing import ZR
E   SystemError: initialization of pairing failed without raising an exception
_____________________________________ ERROR collecting charm/toolbox/securerandom.py _____________________________________
charm/toolbox/securerandom.py:6: in <module>
    from charm.toolbox.conversion import Conversion
charm/toolbox/conversion.py:7: in <module>
    from charm.core.math.integer import integer
E   SystemError: Type does not define the tp_name field.
____________________________________ ERROR collecting charm/toolbox/specialprimes.py _____________________________________
charm/toolbox/specialprimes.py:6: in <module>
    from charm.core.math.integer import integer,isPrime,randomPrime
E   SystemError: Type does not define the tp_name field.
______________________________________ ERROR collecting charm/toolbox/symcrypto.py _______________________________________
charm/toolbox/symcrypto.py:1: in <module>
    from charm.toolbox.paddingschemes import PKCS7Padding
charm/toolbox/paddingschemes.py:3: in <module>
    from charm.toolbox.securerandom import SecureRandomFactory
charm/toolbox/securerandom.py:6: in <module>
    from charm.toolbox.conversion import Conversion
charm/toolbox/conversion.py:7: in <module>
    from charm.core.math.integer import integer
E   SystemError: Type does not define the tp_name field.
_____________________________________ ERROR collecting charm/toolbox/xmlserialize.py _____________________________________
charm/toolbox/pairinggroup.py:3: in <module>
    from charm.core.math.pairing import pairing,pc_element,ZR,G1,G2,GT,init,pair,hashPair,H,random,serialize,deserialize,ismember,order
E   SystemError: initialization of pairing failed without raising an exception

During handling of the above exception, another exception occurred:
charm/toolbox/xmlserialize.py:1: in <module>
    from charm.toolbox.pairinggroup import PairingGroup
charm/toolbox/pairinggroup.py:8: in <module>
    exit(-1)
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_sitebuiltins.py:26: in __call__
    raise SystemExit(code)
E   SystemExit: -1
---------------------------------------------------- Captured stdout -----------------------------------------------------
initialization of pairing failed without raising an exception
_____________________________________ ERROR collecting charm/zkp_compiler/zk_demo.py _____________________________________
charm/toolbox/pairinggroup.py:3: in <module>
    from charm.core.math.pairing import pairing,pc_element,ZR,G1,G2,GT,init,pair,hashPair,H,random,serialize,deserialize,ismember,order
E   SystemError: initialization of pairing failed without raising an exception

During handling of the above exception, another exception occurred:
charm/zkp_compiler/zk_demo.py:1: in <module>
    from charm.toolbox.pairinggroup import PairingGroup,ZR,G1,G2,GT,pair
charm/toolbox/pairinggroup.py:8: in <module>
    exit(-1)
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_sitebuiltins.py:26: in __call__
    raise SystemExit(code)
E   SystemExit: -1
---------------------------------------------------- Captured stdout -----------------------------------------------------
initialization of pairing failed without raising an exception
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 172 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================== 172 error in 3.91 seconds ================================================
make: *** [test] Error 2
                                                                                                                          
charm git/dev  8s
❯ 

```
Cut out most of the errors so that the thread wasn't obnoxiously long. But wanted to show most modules are failing. Is there an easy fix to this?

I tried using the python scripts, but most modules say, "can't find x"

**Comment by jakinyele** [comment]
Haven't had a chance to test python 3.6 on OSX yet. Can you try python 3.5? If so, will need to investigate issues with 3.6.

**Comment by CraigglesO** [comment]
Works great on python 3.5 thanks.

still getting this error:
```
Traceback (most recent call last):
  File "generate_keys.py", line 1, in <module>
    from tpke import dealer, serialize, group
    from charm.toolbox.pairinggroup import PairingGroup,ZR,G1,G2,GT,pair
ImportError: No module named toolbox.pairinggroup
```

But it is probably for some other reason.

**Comment by iamtrask** [comment]
I also couldn't get charm-crypto to work on either 3.6 or 3.5. Both had the same error

>>> from charm.toolbox.pairinggroup import PairingGroup,ZR,G1,G2,GT,pair
initialization of pairing failed without raising an exception

**Comment by iamtrask** [comment]
@jakinyele A friend of mine just tired to install with 3.5 and got the same error as well.

**Comment by iamtrask** [comment]
Spent several hours trying to get this to work to no avail. Help needed

**Comment by lotrgsn-GH** [comment]
Hi,
May I know what version of OS X are you using?
Thanks.

**Comment by iamtrask** [comment]
Mac OSX Sierra... 10.12 I believe.

**Comment by jakinyele** [comment]
Sorry for the delay. I'm still running OS X El Capitan (10.11) and can't reproduce the issue. Perhaps, someone has figured out the issue on 10.12?

**Comment by ikalchev** [comment]
Issue persists on High Sierra (10.13) as well (python 3.6).

**Comment by ikalchev** [comment]
This could be related: https://github.com/cython/cython/issues/1551

I am trying to get configure to use gcc-7, but it keeps using clang instead, so I cannot confirm that the above is really the cause.

**Comment by jakinyele** [comment]
You could modify configure.sh to use gcc instead. See https://github.com/JHUISI/charm/blob/dev/configure.sh#L828

**Comment by ikalchev** [comment]
I tried that already (`echo "CC=gcc-7" >> $config_mk`; this is the gcc executable I got from brew). I also tried changing it in config.mk after ./configure.sh finished and then did make. In both times, clang was used:
```sh
IK-Pro:charm ivankalchev$ ./configure.sh --enable-darwin
IK-Pro:charm ivankalchev$ make
...
Platform: Darwin
...
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DBENCHMARK_ENABLED=1 -Icharm/core/utilities/ -Icharm/core/benchmark/ -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c charm/core/math/pairing/pairingmodule.c -o build/temp.macosx-10.13-x86_64-3.6/charm/core/math/pairing/pairingmodule.o
```
I guess I need to play with it a bit more to see what overrides my overriding. In the mean time, other suggestions are welcome.

**Comment by ikalchev** [comment]
The clang bug I referred to earlier doesn't seem to be the issue here.

I found out that the compilation flags are set from distutils/setuptools. Therefore, you can go to setup.py and add `os.environ["CC"]="gcc-7"`, which will force the extensions to be build with gcc-7. However the issue persists and boils down to:
```sh
IK-Pro:charm ivankalchev$ python3 -c "import charm.core.math.pairing"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemError: initialization of pairing failed without raising an exception
```

**Comment by ikalchev** [comment]
Okay, more info that hopefully will shed some light:

I added `DEBUG 1` to setup.py and put some debug messages in [PyInit_pairing](https://github.com/JHUISI/charm/blob/438a62e392d7157a0effda5c00d4edbf6c9d75bb/charm/core/math/pairing/pairingmodule.c#L2128) to see how far the init goes. The error seems to come from lines 2149/2150 (readiness of `BenchmarkType`).

Following this, I configured with `--disable-benchmark`, but then compilation failed:
```
clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -O0 -g -g -UBENCHMARK_ENABLED -Icharm/core/utilities/ -Icharm/core/benchmark/ -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c charm/core/math/integer/integermodule.c -o build/temp.macosx-10.13-x86_64-3.6/charm/core/math/integer/integermodule.o
charm/core/math/integer/integermodule.c:2377:24: error: no member named 'dBench' in 'struct module_state'
        Py_VISIT(GETSTATE(m)->dBench);
        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/include/python3.6m/objimpl.h:353:13: note: expanded from macro 'Py_VISIT'
        if (op) {
...
```
So, I just commented-out benchmark code from `PyInit_pairing` to see what happens and then the import of pairing was successful. However, doing experiments with the whole of charm (without `--disable-benchmark` this time), I later uncovered this:
```
IK-Pro:charm ivankalchev$ python3 -c "import charm.core.math.integer"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/ivankalchev/Dev/charm-crypto/charm/charm/core/math/integer.cpython-36m-darwin.so, 2): Symbol not found: _size
  Referenced from: /Users/ivankalchev/Dev/charm-crypto/charm/charm/core/math/integer.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/ivankalchev/Dev/charm-crypto/charm/charm/core/math/integer.cpython-36m-darwin.so
```

Based on the above, I think there are two issues here:
1. For some reason `BenchmarkType` fails to initialise.
2. Missing symbol in the `integer` extension lib.

I would guess they are related, but I don't have time to debug further now. @jakinyele any thoughts?

**Comment by ikalchev** [comment]
I think I found and fixed the errors, although I don't know how one of them was introduced.

### 1. `Symbol not found: _size` when importing `charm.core.math.integer`
This comes from what `inline` means for different compilers and standards. There is a `inline size_t size` function in [integermodule.c](charm/core/math/integer/integermodule.c#L69). According to the clang [docs](http://clang.llvm.org/compatibility.html#inline), if the function is not declared static it will result in an undefined symbol. After adding static, the module can be imported successfully.

### 2. `SystemError: initialization of X failed without raising an exception`
Replace X with `integer`, `pairing` or `elliptic_curve`.  All these modules called `PyType_Ready` on `BenchmarkType`. According to the [docs](https://docs.python.org/3.5/c-api/type.html#c.PyType_Ready), this is called to finalise a type object. Since this is already done in the `PyInit_benchmark` then maybe calling it a second time leads to a failure. After removing the calls, the imports are successful.

After addressing 1 and 2, `make test` got me this:
```
============================== test session starts ===============================
platform darwin -- Python 3.6.3, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /Users/ivankalchev/Dev/github/charm, inifile: pytest.ini
collected 181 items / 4 errors                                                    

===================================== ERRORS =====================================
__________________ ERROR collecting charm/schemes/abenc/ac17.py __________________
charm/schemes/abenc/ac17.py:19: in <module>
    from msp import MSP
E   ModuleNotFoundError: No module named 'msp'
_________________ ERROR collecting charm/schemes/abenc/bsw07.py __________________
charm/schemes/abenc/bsw07.py:19: in <module>
    from msp import MSP
E   ModuleNotFoundError: No module named 'msp'
_________________ ERROR collecting charm/schemes/abenc/cgw15.py __________________
charm/schemes/abenc/cgw15.py:19: in <module>
    from msp import MSP
E   ModuleNotFoundError: No module named 'msp'
________________ ERROR collecting charm/schemes/abenc/waters11.py ________________
charm/schemes/abenc/waters11.py:19: in <module>
    from msp import MSP
E   ModuleNotFoundError: No module named 'msp'
!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!
============================ 4 error in 2.19 seconds =============================
make: *** [test] Error 2
```
Which leads me to:
### 3. Fix msp import
The solution to the above is to change that import to `from charm.schemes.abenc.msp import MSP`
After that all tests are green.

Can someone please confirm these changes don't break anything on, e.g., a linux, so I can prepare a pull request?

**Comment by jakinyele** [comment]
Thanks for investigating! I found a different fix for #2 and I've addressed #3 by moving MSP to the toolbox. Testing and will commit soon. Can you confirm on your end as well?

**Comment by ikalchev** [comment]
All three issues (1-3) I pointed out earlier are fixed with this commit: https://github.com/ikalchev/charm/commit/1dabdb1b8b15ed60a0071303cce8b87a303ce2b8

What fix for 2 do you have?

As for 3, I would put the absolute path in the import (i.e. charm.schemes...) wherever msp is located.

Let me know if you would like a pull request for the above commit.

**Comment by jakinyele** [comment]
No need for a pull request. The fix you have for 2 (remove PyType_Ready calls) breaks benchmarking unfortunately. But including the BenchmarkType structure definitions in each module does the trick. Thanks for your help though, @ikalchev!

**Comment by ikalchev** [comment]
Ah, I see. No worries, glad to help.
