### ISSUE TITLE
 ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Reagan1947** [JHUISI/charm#224]
Traceback (most recent call last):
  File "C:/Users/ED_Reagan/PycharmProjects/charm_crypto_pro/charm_crypto_test.py", line 1, in <module>
    from charm.toolbox.pairinggroup import PairingGroup
  File "C:\Python27\Lib\site-packages\Charm_Crypto-0.43-py2.7-win32.egg\charm\__init__.py", line 5, in <module>
    import charm.core.benchmark 
 ImportError: DLL load failed: %1 is not a valid Win32 application

**Comment by jakinyele** [comment]
Closing as part of issue cleanup. This appears to be a support/usage question rather than a bug report. For help, please refer to the updated [README](https://github.com/JHUISI/charm/blob/dev/README.md) and examples. Feel free to reopen if this is still relevant.
