### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by brunotar96** [JHUISI/charm#251]
I installed charm on Alpine Linux in this way: 

1) I executed ./configure.sh
/configure.sh 
Install prefix    /usr/local
data directory    /usr/local/share/charm
binary directory  /usr/local/bin
library directory /usr/local/lib
config directory  /usr/local/etc
Source path       /charm
CFLAGS            -O2 -g 
CHARM_CFLAGS       -m64 -Wall -Wundef -Wwrite-strings -Wmissing-prototypes  -fstack-protector-all -Wendif-labels -Wmissing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-declaration -Wold-style-definition -Wtype-limits
LDFLAGS           -m64 
make              make
python            /usr/bin/python3
python-config     /usr/bin/python3-config
build_ext options build_ext 
install           install
host CPU          x86_64
wget              /usr/bin/wget
gprof enabled     no
profiler          no
static build      no
-Werror enabled   no
integer module    yes
ecc module        yes
pairing module    yes
disable benchmark no
libm found        yes
libgmp found      yes
libpbc found      yes
libcrypto found   yes
Documentation     no

2) make and make install correctly but 

3) when i try to do make test, I have this error: 

initialization of integer failed without raising an exception
========================================================================================= short test summary info ==========================================================================================
ERROR charm/adapters/abenc_adapt_hybrid.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/adapters/dabenc_adapt_hybrid.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/adapters/ibenc_adapt_hybrid.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/adapters/kpabenc_adapt_hybrid.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/adapters/pkenc_adapt_hybrid.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/chamhash_adm05.py - SystemExit: -1
ERROR charm/schemes/chamhash_rsa_hw09.py - SystemExit: -1
ERROR charm/schemes/encap_bchk05.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/joye_scheme.py - SystemExit: -1
ERROR charm/schemes/lem_scheme.py - SystemExit: -1
ERROR charm/schemes/pre_mg07.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/protocol_a01.py - SystemExit: -1
ERROR charm/schemes/protocol_ao00.py - SystemExit: -1
ERROR charm/schemes/abenc/abenc_yct14.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/hibenc/hibenc_bb04.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/hibenc/hibenc_lew11.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/ibenc/ibenc_bf01.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/ibenc/ibenc_ckrs09.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/ibenc/ibenc_waters05.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/ibenc/ibenc_waters05_z.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/pkenc/pkenc_gm82.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/pkenc/pkenc_paillier99.py - SystemExit: -1
ERROR charm/schemes/pkenc/pkenc_rabin.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/pkenc/pkenc_rsa.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/pksig/pksig_cl03.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/pksig/pksig_dsa.py - SystemExit: -1
ERROR charm/schemes/pksig/pksig_rsa_hw09.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/pksig/pksig_schnorr91.py - SystemExit: -1
ERROR charm/schemes/pksig/pksig_waters.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/pksig/pksig_waters05.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/schemes/prenc/pre_nal16.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/adapters/abenc_adapt_hybrid_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/adapters/abenc_adapt_hybrid_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/adapters/dabenc_adapt_hybrid_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/adapters/dabenc_adapt_hybrid_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/adapters/ibenc_adapt_hybrid_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/adapters/ibenc_adapt_hybrid_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/adapters/kpabenc_adapt_hybrid_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/adapters/kpabenc_adapt_hybrid_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/benchmark/benchmark_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/benchmark/benchmark_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/chamhash_adm05_test.py - SystemExit: -1
ERROR charm/test/schemes/chamhash_adm05_test.py - SystemExit: -1
ERROR charm/test/schemes/chamhash_rsa_hw09_test.py - SystemExit: -1
ERROR charm/test/schemes/chamhash_rsa_hw09_test.py - SystemExit: -1
ERROR charm/test/schemes/encap_bchk05_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/encap_bchk05_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/pkenc_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/pkenc_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/pksig_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/pksig_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/rsa_alg_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/rsa_alg_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/hibenc/hibenc_bb04_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/hibenc/hibenc_bb04_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/ibenc/ibenc_bf01_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/ibenc/ibenc_bf01_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/ibenc/ibenc_ckrs09_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/ibenc/ibenc_ckrs09_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/ibenc/ibenc_waters05_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/schemes/ibenc/ibenc_waters05_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/serialize/serialize_test.py - SystemExit: -1
ERROR charm/test/serialize/serialize_test.py - SystemExit: -1
ERROR charm/test/toolbox/conversion_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/toolbox/conversion_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/toolbox/ecgroup_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/toolbox/ecgroup_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/toolbox/paddingschemes_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/toolbox/paddingschemes_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/toolbox/symcrypto_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/test/toolbox/symcrypto_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/toolbox/conversion.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/toolbox/hash_module.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/toolbox/integergroup.py - SystemExit: -1
ERROR charm/toolbox/paddingschemes.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/toolbox/paddingschemes_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/toolbox/paddingschemes_test.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/toolbox/redundancyschemes.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/toolbox/securerandom.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/toolbox/specialprimes.py - SystemError: initialization of integer failed without raising an exception
ERROR charm/toolbox/symcrypto.py - SystemError: initialization of integer failed without raising an exception

**Comment by szyanan** [comment]
Hi, have you solved this problem?

**Comment by lrusso96** [comment]
@brunotar96 @szyanan I had a similar issue when using Python 3.8+

Check it out your Python versions: I have written a [simple guide](https://lrusso96.github.io/blog/cryptography/2021/03/04/charm-setup.html) to install charm on latest Ubuntu systems, hope it could help you.

**Comment by SkylerAusten** [comment]
> @brunotar96 @szyanan I had a similar issue when using Python 3.8+
> 
> Check it out your Python versions: I have written a [simple guide](https://lrusso96.github.io/blog/cryptography/2021/03/04/charm-setup.html) to install charm on latest Ubuntu systems, hope it could help you.

@lrusso96 I followed the steps laid out in your guide, but I keep getting this error when using make:

ImportError: cannot import name 'six' from 'pip._vendor' (/usr/bin/py37/lib/python3.7/site-packages/pip/_vendor/__init__.py)
error: Command '['/usr/bin/py37/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp_7qgynzq', '--quiet', 'hypothesis']' returned non-zero exit status 1.
make: *** [Makefile:51: test] Error 1

Did you see this on your end?  Any idea what's causing it?

**Comment by lrusso96** [comment]
Hi @SkylerAusten try running `pip list` after you activate the virtual Py3.7 environment.
It should list six (in my case it is six v.1.14). Otherwise you should install it through `pip install six`.

Hope it helps!

**Comment by SkylerAusten** [comment]
> Hi @SkylerAusten try running `pip list` after you activate the virtual Py3.7 environment.
> It should list six (in my case it is six v.1.14). Otherwise you should install it through `pip install six`.
> 
> Hope it helps!

Thanks for the swift reply and for your willingness to help!  Oddly enough, running "pip list" and "pip install six" both yield the same output:

└──╼ #pip list
Traceback (most recent call last):
  File "/usr/bin/py37/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/bin/py37/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/bin/py37/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/bin/py37/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/bin/py37/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/usr/bin/py37/lib/python3.7/site-packages/pip/_internal/cli/progress_bars.py", line 7, in <module>
    from pip._vendor import six
ImportError: cannot import name 'six' from 'pip._vendor' (/usr/bin/py37/lib/python3.7/site-packages/pip/_vendor/__init__.py)

I'm not quite sure what would be causing this.  Any suggestions?

**Comment by lrusso96** [comment]
> Thanks for the swift reply and for your willingness to help! Oddly enough, running "pip list" and "pip install six" both yield the same output
> I'm not quite sure what would be causing this. Any suggestions?

@SkylerAusten It seems that your pip is trying to import the six module, but it is not installed (or at least it cannot find it in your py37 environment).

I'm not sure, but it could be an issue with pip itself.
Which version of pip are you using? Run `pip -V` after you activate your virtual environment to know it.
I'm using pip v20.0.2.

**Comment by SkylerAusten** [comment]
I got it working--thanks for all your help!  The guide you posted on your site was a great resource.
