### ISSUE TITLE
make install failed

### ISSUE THREAD

**Issue by tha061** [JHUISI/charm#256]
Hi all, 

My system: Ubuntu 18.04.2
python 3.6.9
I installed gmp-6.2.0, pbc-0.5.14 and openssl-1.0.2l.
I tried to install this version "Charm-Crypto-0.42.tar.gz." https://github.com/JHUISI/charm/downloads
However, I got the error below.

/usr/bin/python3 setup.py install
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.24.tar.gz
Traceback (most recent call last):
  File "/home/sec-user/ThamNguyen/Charm-Crypto-0.42/distribute_setup.py", line 143, in use_setuptools
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    use_setuptools() #bootstrap installs Distribute if not installed
    src = urlopen(url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: SSL is required
Makefile:96: recipe for target 'install' failed
make: *** [install] Error 1

Have you encountered this error? I did some workaround but couldn't find a solution. 
Any help would be much appreciated.

**Comment by tha061** [comment]
For those who are having the same problem installing charm:
Following the instruction below let you install the latest version of charm in one minute.

https://github.com/JHUISI/charm/commit/1247912e721ba99111f1ae9dbdc96b693ba0a111
